### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koivunen** [Lounaispaikka/virma_lipas#1]
- [X] Lataa lipastiedot
- [ ] Rajaa haku haluttuihin (geo tai kaupunkitunnukset)
- [ ] Rajaa tarkasti jos geo
- [ ] Heuristiikan tarkennus
- [ ] Luo crontabi
- [ ] Yhdistä virmadatan kanssa
